"""
Lab Experiment: Orchestrating Multi-Agent Systems with CrewAI
BTech Students - Simple Research & Writing Crew
"""

import os
import sys

# Ensure UTF-8 output encoding for Windows terminal
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8')

from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM

# -------------------------------------------------
# 1. Load API keys from .env file
# -------------------------------------------------
load_dotenv()   # Automatically reads .env in the same folder

# Configure LLM based on environment variables loaded from .env
openai_api_key = os.getenv("OPENAI_API_KEY")
openrouter_api_key = os.getenv("OPENROUTER_API_KEY")
model_name = os.getenv("model_name")

if openai_api_key:
    llm = LLM(
        model="gpt-4o-mini",
        api_key=openai_api_key
    )
elif openrouter_api_key:
    model_id = f"openrouter/{model_name}" if model_name and not model_name.startswith("openrouter/") else "openrouter/nvidia/nemotron-3-ultra-550b-a55b:free"
    llm = LLM(
        model=model_id,
        api_key=openrouter_api_key,
        base_url="https://openrouter.ai/api/v1"
    )
else:
    raise ValueError("Neither OPENAI_API_KEY nor OPENROUTER_API_KEY found in .env file!")

# -------------------------------------------------
# 2. Define Agents (Role-based specialists)
# -------------------------------------------------

# Agent 1: Researcher
researcher = Agent(
    role="Senior Research Analyst",
    goal="Conduct thorough research on the given topic and extract key facts, trends, and insights",
    backstory=(
        "You are an experienced research analyst with strong analytical skills. "
        "You excel at finding accurate, up-to-date information and summarizing it clearly."
    ),
    verbose=True,          # Shows thinking process (useful for lab demo)
    allow_delegation=False,
    llm=llm
)

# Agent 2: Writer
writer = Agent(
    role="Technical Content Writer",
    goal="Transform research findings into a clear, well-structured and engaging report",
    backstory=(
        "You are a professional technical writer known for converting complex research "
        "into easy-to-understand, well-organized reports suitable for students and professionals."
    ),
    verbose=True,
    allow_delegation=False,
    llm=llm
)

# -------------------------------------------------
# 3. Define Tasks
# -------------------------------------------------

research_task = Task(
    description=(
        "Research the topic: '{topic}'. "
        "Focus on key concepts, recent developments, important applications, "
        "challenges, and future trends. Collect accurate and relevant information."
    ),
    expected_output=(
        "A detailed research summary containing:\n"
        "- Key concepts\n"
        "- Recent developments\n"
        "- Applications\n"
        "- Challenges\n"
        "- Future outlook"
    ),
    agent=researcher
)

writing_task = Task(
    description=(
        "Using the research findings, write a clear and professional report on '{topic}'. "
        "Make it well-structured with headings and suitable for BTech students."
    ),
    expected_output=(
        "A well-formatted markdown report with the following sections:\n"
        "1. Introduction\n"
        "2. Key Concepts\n"
        "3. Recent Developments\n"
        "4. Applications\n"
        "5. Challenges\n"
        "6. Conclusion & Future Scope"
    ),
    agent=writer,
    context=[research_task]   # Writer receives output of researcher
)

# -------------------------------------------------
# 4. Create the Crew (Orchestration)
# -------------------------------------------------

crew = Crew(
    agents=[researcher, writer],
    tasks=[research_task, writing_task],
    process=Process.sequential,   # Tasks run one after another
    verbose=True
)

# -------------------------------------------------
# 5. Run the Multi-Agent System
# -------------------------------------------------

if __name__ == "__main__":
    topic = "Multi-Agent Systems in Artificial Intelligence"
    
    print("\n" + "="*60)
    print("Starting Multi-Agent Crew for topic:", topic)
    print("="*60 + "\n")

    result = crew.kickoff(inputs={"topic": topic})

    print("\n" + "="*60)
    print("FINAL REPORT GENERATED BY THE CREW")
    print("="*60)
    print(result)